title: Charlas
author:
  name: by Alicia PÃ©rez
  # email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  
url: https://aliciapj.github.io/talks
baseurl: ''

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

  # generate social links in footer
  social_links:
    twitter: alipeji
    github:  aliciapj
    linkedin: aliciapj
    telegram: aliciapj

# Build settings
theme: minima

plugins:
 - jekyll-feed
